# Generated by Django 5.0.6 on 2024-06-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('userId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contacts', models.TextField()),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('supplier', 'Supplier'), ('wholesaler', 'Wholesaler')], default='farmer', max_length=15)),
            ],
        ),
    ]
