# Generated by Django 5.0.6 on 2024-06-16 18:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to),
        ),
    ]
