# Generated by Django 5.0.6 on 2024-06-20 15:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userdetail_profilepic'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('unit_name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to=api.models.upload_to)),
            ],
        ),
    ]
