# Generated by Django 5.0.6 on 2024-07-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_order_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='order',
            name='itemId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
