# Generated by Django 5.0.6 on 2024-07-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_order_item_order_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_by',
            field=models.CharField(choices=[('wholesaler', 'Wholesaler'), ('farmer', 'Farmer')], default='buyer', max_length=15),
        ),
    ]
